### ISSUE TITLE
Please tag an official release

### ISSUE THREAD

**Issue by SnarkBoojum** [arminbiere/cadiback#3]
I would like to package cadiback in Debian. The motivation is to update the cryptominisat package to its latest upstream where cadiback is a dependency.

But to package a piece of software, Debian prefers official releases and there are none yet.

Can you do an official release? A simple "git tag -s v3.14159" followed by a "git push --all" is all it takes to make an official release on github as far as I know (3.14159 is just an example, of course...).

Thanks!

**Comment by arminbiere** [comment]
Done.
